name: Aap_job
description: Aap job provide a vast experience for people who are looking for right candidate and people who are lookig for jobs.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 26.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.3
  get: ^4.6.5
  get_it: ^6.0.0
  dio: ^5.0.0
  intl: ^0.17.0
  firebase_messaging: ^14.2.1
  video_player: ^2.5.1
  connectivity_plus: ^3.0.2
  shimmer: ^2.0.0
  google_language_fonts: ^2.0.0
  http: ^0.13.5
  flutter_downloader: ^1.10.1+2
  path_provider: ^2.0.12
#  location: ^4.4.0
#  camera: ^0.10.3
  google_maps_flutter: ^2.2.3
#  flutter_uploader: ^1.2.1
  files_uploader: ^0.1.1
  fluttertoast: ^8.1.2
  shared_preferences: ^2.0.13
  flutter_local_notifications: 9.8.0+1
  firebase_core: ^2.4.1 # Needed for Crashlytics below
  lottie: ^2.2.0
  google_sign_in: ^5.4.4
  google_fonts: ^4.0.1
  firebase_auth: ^4.2.8
  camerawesome: ^1.2.1
#  geocoder: ^0.2.1
  image_picker: ^0.8.6+2
  geocoding: ^2.1.0
#  cached_video_player: ^2.0.4
#  new
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.5
  file_picker: ^5.0.1
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.3.4
  geolocator: ^9.0.2
  firebase_core_platform_interface: ^4.5.1
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  flutter_typeahead: ^4.3.7
  launch_review: ^3.0.1
  flutter_share: ^2.0.0
  pdf_viewer_plugin: ^2.0.1
  sms_autofill: ^2.2.0
  image_cropper: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  package_info_plus: ^1.3.0
  firebase_database: ^10.1.0
  flutter_contacts: ^1.1.6
  custom_clippers: ^2.0.0
  photo_manager: ^2.5.0
  the_apple_sign_in: ^1.1.1

dependency_overrides:
#  razorpay_flutter: ^1.3.4
camera_android:
  git:
    url: https://github.com/bottlepay/plugins.git
    path: packages/camera/camera_android
    ref: e1a4dba770da9bc3cf9f858bac6837083f8b9059

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  test: ^1.19.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/appicon.png
    - assets/images/applesignin.png
    - assets/images/facebookbtn.png
    - assets/images/googlebtn.png
    - assets/images/map.png
    - assets/images/hr.png
    - assets/images/candidate.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/city.png
    - assets/images/opening.png
    - assets/images/rupe.png
    - assets/images/gst.png
    - assets/images/company.png
    - assets/images/fssai.png
    - assets/images/pan.png
    - assets/images/shop.png
    - assets/images/call.png
    - assets/images/telegram.png
    - assets/images/msme.png
    - assets/images/coin.png
    - assets/images/closejob.png
    - assets/images/editjob.png
    - assets/images/WhatsApp.png
    - assets/lottie/hiring.json
    - assets/lottie/addprofile.json
    - assets/lottie/blinkingeyes.json
    - assets/lottie/humanresources.json
    - assets/lottie/liveprofile.json
    - assets/lottie/login.json
    - assets/lottie/profile.json
    - assets/lottie/welcome.json
    - assets/lottie/bell.json
    - assets/lottie/support.json
    - assets/lottie/interview.json
    - assets/lottie/consultancy.json
    - assets/lottie/coin.json
    - assets/lottie/thankyou.json
    - assets/lottie/upgrade.json
    - assets/lottie/whatsapp.json
    - assets/lottie/callicon.json
    - assets/lottie/telegram.json
    - assets/lottie/arrowright.json
    - assets/lottie/mailicon.json
    - assets/lottie/website.json
    - assets/lottie/purchasedetail.json
    - assets/lottie/proceedtopayment.json
    - assets/lottie/buynow.json
    - assets/lottie/location.json
    - assets/lottie/add.json
    - assets/lottie/proceedtopayment2.json
    - assets/lottie/proceedtopayment3.json
    - assets/lottie/worried.json
    - assets/lottie/comingsoon.json
    - assets/lottie/buynow2.json
    - assets/lottie/share.json
    - assets/lottie/locatione.json
    - assets/lottie/gps.json
    - assets/lottie/chat_icon.json
    - assets/lottie/notification_bell.json
    - assets/lottie/profileimage.json
    - assets/lottie/error.json
    - assets/lottie/profilene.json
    - assets/lottie/shareapp.json
    - assets/lottie/starss.json
    - assets/images/opps_internet.png
    - assets/images/no_data.png
    - assets/images/cemara.png
    - assets/images/gallery.png
    - assets/images/pdficon.png
    - assets/language/
#  fonts:
#    - family: Permanent Marker
#      fonts:
#        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/appicone.png"
