// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpQUGKhLlB0fkZWH1LMA8uAd9hDQ0Q28',
    appId: '1:798937931743:android:d147c1fae12abb516eee6a',
    messagingSenderId: '798937931743',
    projectId: 'aap-job',
    storageBucket: 'aap-job.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAerh06KKiObixPF-A4lk6AJ1S43MFvUNs',
    appId: '1:798937931743:ios:fd1b6caf5d8c88db6eee6a',
    messagingSenderId: '798937931743',
    projectId: 'aap-job',
    storageBucket: 'aap-job.appspot.com',
    androidClientId: '798937931743-1ncc0alm0aeohpe6it0eqspvti89pbv0.apps.googleusercontent.com',
    iosClientId: '798937931743-p6k71cf4lr6o4e3a152m8q6bgfngspvq.apps.googleusercontent.com',
    iosBundleId: 'com.unick.aapjob',
  );
}
